# Generated by Django 3.1.1 on 2020-09-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockpaperscissors', '0005_match_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatch',
            name='move',
            field=models.CharField(choices=[('r', 'rock'), ('p', 'paper'), ('s', 'scissors')], max_length=1, null=True),
        ),
    ]
