# Generated by Django 3.1.1 on 2020-10-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rockpaperscissors', '0007_auto_20201003_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstatus',
            old_name='user',
            new_name='name',
        ),
    ]
