# Generated by Django 3.1.1 on 2020-10-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rockpaperscissors', '0008_auto_20201003_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playermatch',
            old_name='user',
            new_name='player',
        ),
    ]
