# Generated by Django 3.1.1 on 2020-10-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockpaperscissors', '0009_auto_20201004_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
