# Generated by Django 3.1.1 on 2020-10-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockpaperscissors', '0010_auto_20201012_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatch',
            name='move',
            field=models.CharField(choices=[('rock', 'rock'), ('paper', 'paper'), ('scissors', 'scissors')], max_length=8, null=True),
        ),
    ]
