# Generated by Django 3.1.1 on 2020-10-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockpaperscissors', '0011_auto_20201017_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatch',
            name='move',
            field=models.CharField(choices=[('r', 'rock'), ('p', 'paper'), ('s', 'scissors')], max_length=1, null=True),
        ),
    ]
