# Generated by Django 3.1.1 on 2020-11-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockpaperscissors', '0012_auto_20201017_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatch',
            name='round_start_time',
            field=models.IntegerField(null=True),
        ),
    ]
